# Site wide configuration

title:            williamstome
locale:           en_US
url:              http://williamstome.github.io/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Tom Williams
  avatar: https://en.gravatar.com/userimage/26616054/e6f3322a7a49fe676683654ec3dbafce.jpg?size=200
  bio: "Graduate Researcher in Human-Robot Interaction and Natural-Language Dialogues"
  email: williams@cs.tufts.edu
  disqus-shortname: williamstome
  twitter: 
  facebook: #username
  google:
    plus: 
    analytics: UA-43501910-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: #username
  stackoverflow: #username
  linkedin: williamstome
  instagram: #username
  lastfm: williamstome
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  mendeley: tom-williams23
  scholar: qg_aiScAAAAJ

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
